# Generated by Django 4.0.4 on 2022-05-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.level')),
            ],
            options={
                'verbose_name': 'Word Category',
                'verbose_name_plural': 'Word Categories',
                'ordering': ('id', 'category', 'level'),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translate', models.CharField(max_length=255)),
                ('audio_path', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.word_category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.level')),
            ],
            options={
                'ordering': ('id', 'word', 'translate', 'category', 'level'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.level')),
                ('tips', models.ManyToManyField(blank=True, to='database.tip')),
                ('words', models.ManyToManyField(blank=True, to='database.word')),
                ('words_categories', models.ManyToManyField(blank=True, to='database.word_category')),
            ],
            options={
                'ordering': ('id', 'level'),
            },
        ),
    ]
