# Generated by Django 4.0.4 on 2022-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='word_category',
            old_name='name',
            new_name='category',
        ),
    ]
