# Generated by Django 4.0.4 on 2022-05-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_question_rename_name_level_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='database.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='words',
            field=models.ManyToManyField(blank=True, to='database.word'),
        ),
        migrations.AlterField(
            model_name='user',
            name='words_categories',
            field=models.ManyToManyField(blank=True, to='database.word_category'),
        ),
    ]
