# Generated by Django 4.0.4 on 2022-05-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_user_level_alter_user_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.level'),
        ),
    ]
